CREATE TABLE [dbo].[ESTUDIANTE]
(
[IDESTUDIANTE] [int] NOT NULL,
[CIESTUDIANTE] [numeric] (10, 0) NULL,
[NOMBREESTUDIANTE] [text] COLLATE Modern_Spanish_CI_AS NULL,
[APELIIDOESTUDIANTE] [text] COLLATE Modern_Spanish_CI_AS NULL,
[TELEFONOESTUDIANTE] [int] NULL,
[DIRECCIONESTUDIANTE] [char] (20) COLLATE Modern_Spanish_CI_AS NULL,
[FECHANAC] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESTUDIANTE] ADD CONSTRAINT [PK_ESTUDIANTE] PRIMARY KEY NONCLUSTERED  ([IDESTUDIANTE]) ON [PRIMARY]
GO
