CREATE TABLE [dbo].[MAESTRO]
(
[IDPROFESOR] [int] NOT NULL,
[NOMBREPR] [text] COLLATE Modern_Spanish_CI_AS NULL,
[APELLIDOPR] [text] COLLATE Modern_Spanish_CI_AS NULL,
[DIRECCIONPR] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[TELEFONOPR] [numeric] (10, 0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTRO] ADD CONSTRAINT [PK_MAESTRO] PRIMARY KEY NONCLUSTERED  ([IDPROFESOR]) ON [PRIMARY]
GO
