CREATE TABLE [dbo].[NOTAS]
(
[IDNOTAS] [int] NOT NULL,
[IDMATERIA] [int] NULL,
[IDESTUDIANTE] [int] NULL,
[IDPROFESOR] [int] NULL,
[NOTA1] [float] NULL,
[NOTA2] [float] NULL,
[NOTA3] [float] NULL,
[NOTA4] [float] NULL,
[NOTAFINAL] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NOTAS] ADD CONSTRAINT [PK_NOTAS] PRIMARY KEY NONCLUSTERED  ([IDNOTAS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_7_FK] ON [dbo].[NOTAS] ([IDESTUDIANTE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_6_FK] ON [dbo].[NOTAS] ([IDMATERIA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_12_FK] ON [dbo].[NOTAS] ([IDPROFESOR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NOTAS] ADD CONSTRAINT [FK_NOTAS_RELATIONS_ESTUDIAN] FOREIGN KEY ([IDESTUDIANTE]) REFERENCES [dbo].[ESTUDIANTE] ([IDESTUDIANTE])
GO
ALTER TABLE [dbo].[NOTAS] ADD CONSTRAINT [FK_NOTAS_RELATIONS_MAESTRO] FOREIGN KEY ([IDPROFESOR]) REFERENCES [dbo].[MAESTRO] ([IDPROFESOR])
GO
ALTER TABLE [dbo].[NOTAS] ADD CONSTRAINT [FK_NOTAS_RELATIONS_MATERIA] FOREIGN KEY ([IDMATERIA]) REFERENCES [dbo].[MATERIA] ([IDMATERIA])
GO
