CREATE TABLE [dbo].[MATERIA]
(
[IDMATERIA] [int] NOT NULL,
[IDPROFESOR] [int] NULL,
[NOMBREMATERIA] [text] COLLATE Modern_Spanish_CI_AS NULL,
[CURSO] [varchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[SECCION] [text] COLLATE Modern_Spanish_CI_AS NULL,
[MODALIDAD] [text] COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MATERIA] ADD CONSTRAINT [PK_MATERIA] PRIMARY KEY NONCLUSTERED  ([IDMATERIA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_10_FK] ON [dbo].[MATERIA] ([IDPROFESOR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MATERIA] ADD CONSTRAINT [FK_MATERIA_RELATIONS_MAESTRO] FOREIGN KEY ([IDPROFESOR]) REFERENCES [dbo].[MAESTRO] ([IDPROFESOR])
GO
