CREATE TABLE [dbo].[REPRESENTANTE]
(
[IDREPRESENTANTE] [int] NOT NULL,
[IDESTUDIANTE] [int] NULL,
[CIREP] [numeric] (10, 0) NULL,
[NOMBREREPRESENTANTE] [text] COLLATE Modern_Spanish_CI_AS NULL,
[APELLIDOREPRESENTANTE] [text] COLLATE Modern_Spanish_CI_AS NULL,
[FECHANACREP] [datetime] NULL,
[TELEFONOREPRESENTANTE] [numeric] (10, 0) NULL,
[DIRECCIONREPRESENTANTE] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REPRESENTANTE] ADD CONSTRAINT [PK_REPRESENTANTE] PRIMARY KEY NONCLUSTERED  ([IDREPRESENTANTE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_8_FK] ON [dbo].[REPRESENTANTE] ([IDESTUDIANTE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REPRESENTANTE] ADD CONSTRAINT [FK_REPRESEN_RELATIONS_ESTUDIAN] FOREIGN KEY ([IDESTUDIANTE]) REFERENCES [dbo].[ESTUDIANTE] ([IDESTUDIANTE])
GO
